# Generated by Django 4.1.1 on 2022-10-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGames',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='Title')),
                ('rating', models.IntegerField(db_column='Rating')),
                ('preordered', models.BooleanField(blank=True, db_column='PreOrdered', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('excitement', models.TextField(blank=True, db_column='Excitement', null=True)),
                ('platform', models.TextField(db_column='Platform')),
                ('data_created', models.DateTimeField(blank=True, db_column='Data_Created', null=True)),
            ],
            options={
                'db_table': 'Video_Games',
            },
        ),
    ]
