# Generated by Django 4.1.1 on 2022-10-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_Created', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
